{
 "title": "네이버 클라우드1기",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$Namespace\"}, pod)"
   },
   { "name": "duration", "query": "2m,5m,10m,30m,1h" },
   {
    "name": "node",
    "query": "label_values(node_uname_info,kubernetes_node)"
   },
   {
    "name": "instance",
    "query": "query_result(node_uname_info{kubernetes_node=\"$node\"})"
   }
  ]
 },
 "panels": [
  { "title": "클러스터 요약", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "마스터 정상 가동률",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\navg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}))[$duration:5m])\n)"
    }
   ]
  },
  {
   "title": "노드 현황",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{node}}" },
    {
     "expr": " (count by (node)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))"
    },
    {
     "expr": "max\n  by(node) (max by(instance) (kubelet_running_pod_count{job=\"kubelet\",metrics_path=\"/metrics\"})\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})"
    },
    {
     "expr": "sum by (node)(label_replace(instance:node_cpu:ratio + on(instance) group_left(nodename) \nnode_uname_info,\"node\",\"$1\",\"nodename\", \"(.+)\") ) / sum by (node)(kube_node_status_capacity{resource=\"cpu\"})"
    },
    { "expr": "kube_node_role" },
    {
     "expr": "label_replace(up{job=\"kubernetes-nodes\"}, \"node\", \"$1\", \"instance\", \"(.+)\")"
    },
    {
     "expr": "label_replace(avg by (kubernetes_node) (time() - node_boot_time_seconds), \"node\", \"$1\", \"kubernetes_node\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "네임스페이스",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": " count(kube_namespace_created)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Cluster Metrices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "노드 CPU 사용률",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (kubernetes_node)",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "노드 메모리 사용량",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_Active_bytes", "legendFormat": "{{ kubernetes_node }}" }
   ]
  },
  {
   "title": "노드 네트워크 평균 송신/수신 트래픽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_network_transmit_bytes_total[5m])) by (kubernetes_node)",
     "legendFormat": "{{ kubernetes_node }}-transmit"
    },
    {
     "expr": "avg(rate(node_network_receive_bytes_total[5m])) by (kubernetes_node)* -1",
     "legendFormat": "{{ kubernetes_node }}-receive"
    }
   ]
  },
  {
   "title": "노드 상태",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"kubernetes-nodes\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "노드 m-k8s", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU 점유율",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\", kubernetes_node=\"$node\"}[5m]))"
    }
   ]
  },
  {
   "title": "메모리 점유율",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{kubernetes_node=\"m-k8s\"}-node_memory_MemAvailable_bytes{kubernetes_node=\"m-k8s\"})/node_memory_MemTotal_bytes{kubernetes_node=\"m-k8s\"}"
    }
   ]
  },
  {
   "title": "디스크 사용률(%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{kubernetes_node=\"$node\"} - node_filesystem_avail_bytes{kubernetes_node=\"$node\"}) by (kubernetes_node) / sum(node_filesystem_size_bytes{kubernetes_node=\"$node\"}) by (kubernetes_node)"
    }
   ]
  },
  {
   "title": "CPU 코어",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_node_status_allocatable_cpu_cores{node=\"$node\"}"
    }
   ]
  },
  {
   "title": "File descriptor / Context switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "used filefd" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}",
     "legendFormat": "used filefd"
    },
    {
     "expr": "rate(node_context_switches_total{instance=~\"$instance\"}[$duration])",
     "legendFormat": "switches"
    }
   ]
  },
  {
   "title": "Disk IOPS 완료",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 19 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$instance\"}[$duration])",
     "legendFormat": "{{device}}_Reads"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$instance\"}[$duration])",
     "legendFormat": "{{device}}_Writes"
    },
    {
     "expr": "node_disk_io_now{instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "메모리",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "machine_memory_bytes{instance=\"$node\"}"
    }
   ]
  },
  { "title": "$Namespace Namespace Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "$Pod Pod CPU 사용률",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", pod=~\"$Pod\", container!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "$Pod Pod 메모리 사용량",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$Namespace\", pod=~\"$Pod\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "API 서버 응답 시간(5분/SLA 99%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Pod 상태",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"$Pod\", namespace=~\"$Namespace\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  }
 ]
}